config/routes.rb
Rails.application.routes.draw do

resources :restaurants, except: :destroy do
  resources :ratings, only: [:create, :new]
end

end

app/models/rating.rb
class Rating < ActiveRecord::Base
belongs_to :restaurant

validates :rating, presence: true, :inclusion => 1..5
validates :body, presence: true

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
has_many :ratings

validates :name, presence: true
validates :address, presence: true
validates :city, presence: true
validates :state, presence: true
validates :zip_code, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

def create
@restaurant = Restaurant.find(params[:restaurant_id])
@rating = @restaurant.ratings.create(ratings_params)
@rating.save
redirect_to restaurant_path(@restaurant)
end

def new
  @restaurant = Restaurant.find(params[:restaurant_id])
  @rating = Rating.new
end


private
def ratings_params
  params.require(:rating).permit(:rating, :body)
end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all.order(created_at: :desc).limit(10)
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant
    else
      render 'new'
    end
  end


private
  def restaurant_params
    params.require(:restaurant).permit(:name,:address,:city,:state,:zip_code,:description,:category)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoodEats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/ratings/new.html.erb
<%= form_for [@restaurant, @rating] do |f| %>
<p>
<%= f.label :rating %><br>
<%= f.text_field :rating %>
</p>
<p>
<%= f.label :description %> <br>
<%= f.text_area :body %>
</p>

<%=f.submit "Submit Rating"%>
<% end %>

app/views/restaurants/index.html.erb
<h1> All Our Restaurants </h1>
<% @restaurants.each do |restaurant| %>
<ul>
<li>
<%= link_to "#{restaurant.name}", restaurant_path(restaurant) %>
</li>
</ul>
<% end %>

<%= link_to "Add a Restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<%= form_for @restaurant do |f| %>
<p>
<%= f.label :name %> <br>
<%= f.text_field :name %>
</p>
<p>
<%= f.label :address %> <%= f.text_field :address %><br>
<%= f.label :city %> <%= f.text_field :city %> <br>
<%= f.label :state %> <%= f.text_field :state %> <br>
<%= f.label :zip_code %> <%= f.text_field :zip_code %> <br>
</p>
<p>
<%= f.label :description %><br>
<%= f.text_area :description %>
</p>
<p>
<%= f.label :category %> <br>
<%= f.text_field :category %>
</p>
<%=f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %></h2>
Location: <%="#{@restaurant.address}, #{@restaurant.city}, #{@restaurant.state}, #{@restaurant.zip_code}" %>
<ul>
<li>
Description:
<%= @restaurant.description %>
</li><br><br>
<li>
Category:
<%= @restaurant.category %>
</li>
</ul>

<h2> Ratings </h2>
<% @restaurant.ratings.each do |row| %>
<p>
Rating: <%= row.rating %><br>
Description: <%= row.body %></p>
<br>
<% end %><br>
<%= link_to 'Add Rating', new_restaurant_rating_path(@restaurant) %><br>

<%= link_to 'Restaurants', restaurants_path %>